### ISSUE TITLE
Error when attempt to discover 1pm plus  

### ISSUE THREAD

**Issue by tomerhas** [alexryd/homebridge-shelly-ng#10]
Failed to add discovered device (id: shellyplus1pm-441793ceexxx): Cannot read property 'toUpperCase' of undefined

**Comment by tomerhas** [comment]
> Try starting homebridge in debug mode to get more info about the error.

[Shelly NG] Failed to add discovered device (id: shellyplus1pm-441793ceef40): Cannot read property 'toUpperCase' of undefined
[2/20/2022, 8:22:15 AM] [Shelly NG] TypeError: Cannot read property 'toUpperCase' of undefined
    at Function.getClass (/usr/lib/node_modules/homebridge-shelly-ng/node_modules/shellies-ng/src/devices/base.ts:114:40)
    at Shellies.handleDiscoveredDevice (/usr/lib/node_modules/homebridge-shelly-ng/node_modules/shellies-ng/src/shellies.ts:343:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by alexryd** [comment]
That's strange. Seems like your device doesn't specify its model designation. Can you visit `http://<ip-address>/shelly` with the IP address of your device and post the result here?

**Comment by tomerhas** [comment]
> That's strange. Seems like your device doesn't specify its model designation. Can you visit `http://<ip-address>/shelly` with the IP address of your device and post the result here?

sure ....

{"name":null,"id":"shellyplus1pm-441793ceef40","mac":"441793CEEF40","gen":2,"fw_id":"20220117-162947/0.9.3-g354c141","ver":"0.9.3","app":"Plus1PM","auth_en":false,"auth_domain":null}

**Comment by zscgeek** [comment]
It does indeed. I can confirm it fixes the problem.
