### ISSUE TITLE
Current Consumption negative value warning

### ISSUE THREAD

**Issue by somekindofrob** [alexryd/homebridge-shelly-ng#115]
I recently found the following logs and I believe that these warnings that occur almost every minute in the log slow down the homebridge and may even cause it to fail regularly.

[homebridge-shelly-ng] This plugin generated a warning from the characteristic 'Current Consumption': characteristic was supplied illegal value: number -1.3 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.

I have 2x Shelly Pro 4PM installed for plugs and lights. They all seem to run fine, a negative consumption value doesn't make any sense in this configuration.

Thanks a lot for any help :)

**Comment by klausbreyer** [comment]
I found this via search. I have something similar. I am running the fork https://github.com/cubi1337/homebridge-shelly-ds9 because I need support for gen3 devices. 

It just happens to me every other week. Not often, but sometimes. 

```
[03/04/2024, 07:02:01] [homebridge-shelly-ds9] This plugin generated a warning from the characteristic 'Current Consumption': characteristic was supplied illegal value: number -3.8000000000000003 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
[03/04/2024, 07:02:01] [homebridge-shelly-ds9] Error: 
    at Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at Service.updateCharacteristic (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at PowerMeterAbility.apowerChangeHandler (/var/lib/homebridge/node_modules/homebridge-shelly-ds9/src/abilities/power-meter.ts:90:18)
    at Switch.emit (/var/lib/homebridge/node_modules/homebridge-shelly-ds9/node_modules/eventemitter3/index.js:181:35)
    at Switch.update (/var/lib/homebridge/node_modules/homebridge-shelly-ds9/node_modules/shellies-ds9/src/components/base.ts:138:12)
    at ShellyPlus2PmRev1.statusUpdateHandler (/var/lib/homebridge/node_modules/homebridge-shelly-ds9/node_modules/shellies-ds9/src/devices/base.ts:315:35)
    at WebSocketRpcHandler.emit (/var/lib/homebridge/node_modules/homebridge-shelly-ds9/node_modules/eventemitter3/index.js:181:35)
    at WebSocketRpcHandler.handleMessage (/var/lib/homebridge/node_modules/homebridge-shelly-ds9/node_modules/shellies-ds9/src/rpc/websocket.ts:378:12)
[03/04/2024, 07:07:39] [Homebridge UI] [homebridge] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[03/04/2024, 07:07:39] [Homebridge UI] [homebridge-shelly-ds9] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[03/04/2024, 07:07:39] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[03/04/2024, 07:07:39] [Homebridge UI] [homebridge-shelly-ds9] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[03/04/2024, 07:07:39] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
```

**Comment by klausbreyer** [comment]
Just for context: such a thing is easily possible, when you have a solar power device plugged in behind a shelly :) 
![IMG_5790](https://github.com/alexryd/homebridge-shelly-ng/assets/32771/906e5aa1-2a8e-4a5d-9fa4-c2b7684d0072)
