### ISSUE TITLE
Version 1.3.0 Cannot read properties of undefined

### ISSUE THREAD

**Issue by MaDDeePee** [alexryd/homebridge-shelly-ng#22]
Hello,

with 1.3.0 i am getting this:

`TypeError: Cannot read properties of undefined (reading 'reconnectInterval')
    at new PlatformOptions (/volume1/@appdata/homebridge/lib/node_modules/homebridge-shelly-ng/src/config.ts:107:33)
    at new ShellyPlatform (/volume1/@appdata/homebridge/lib/node_modules/homebridge-shelly-ng/src/platform.ts:154:20)
    at /volume1/@appdata/homebridge/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/volume1/@appdata/homebridge/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/volume1/@appdata/homebridge/lib/node_modules/homebridge/src/server.ts:159:29)`

Homebridge 1.4.0.
1.3.0_beta is fine. Do i need to clear cache or something? :)

Btw: Happy Easter!

**Comment by Sebbo02** [comment]
Just to confirm: same issue here after updating from the beta

**Comment by alexryd** [comment]
Thanks! Version 1.3.1 fixes this!

**Comment by MaDDeePee** [comment]
Yes, all ok now! Thank you!
