### ISSUE TITLE
mDNS Error

### ISSUE THREAD

**Issue by john-h-watson** [alexryd/homebridge-shelly-ng#7]
Thank you so much for your great work developing this plugin!

It works like a charm with my Shelly 1 Plus. 

However, I'm getting the following error about once or twice a minute on the homebridge log: 
`An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)`

I have my Shellys on a different VLAN. Could you specify what this error means exactly? I'm guessing I have to update my firewall setting to make it disappear. I'm a bit confused why it has no problem discovering my devices, though. 

Here is a longer excerpt from the homebridge log:
```
[2/7/2022, 2:27:52 PM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge xxxx) is running on port 51504.
[2/7/2022, 2:27:52 PM] [Shelly] Admin server is running on port 8181
[2/7/2022, 2:27:52 PM] [Shelly NG] mDNS device discovery started
[2/7/2022, 2:27:53 PM] [Shelly NG] [WoZi Tisch] Device added
[2/7/2022, 2:28:09 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:28:09 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:28:27 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:28:49 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:28:49 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:29:57 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:29:57 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:31:10 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:31:10 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:32:14 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:32:47 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:32:47 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:34:18 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:34:18 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:34:52 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:35:00 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 2:35:00 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
```
[this goes on and on]

**Comment by alexryd** [comment]
I honestly have no idea what that error means. Maybe some device in your network is advertising malformed messages?

You can launch homebridge in debug mode to get a stack trace of the error.

Either way, unless you want to discover new devices, you can disable the mDNS service by adding this to the config:

```
"mdns": {
  "enable": false
}
```

**Comment by john-h-watson** [comment]
Thank you so much for your prompt reply! 

The debug mode gives the following additional information:
```
[2/7/2022, 3:47:11 PM] [Shelly NG] An error occurred in the mDNS device discovery service: Cannot decode name (bad pointer)
[2/7/2022, 3:47:11 PM] [Shelly NG] Error: Cannot decode name (bad pointer)
    at Object.name.decode (/usr/local/lib/node_modules/homebridge-shelly-ng/node_modules/dns-packet/index.js:83:15)
    at Object.rnsec.decode (/usr/local/lib/node_modules/homebridge-shelly-ng/node_modules/dns-packet/index.js:1147:28)
    at Object.answer.decode (/usr/local/lib/node_modules/homebridge-shelly-ng/node_modules/dns-packet/index.js:1391:18)
    at decodeList (/usr/local/lib/node_modules/homebridge-shelly-ng/node_modules/dns-packet/index.js:1565:19)
    at Object.exports.decode (/usr/local/lib/node_modules/homebridge-shelly-ng/node_modules/dns-packet/index.js:1506:12)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-shelly-ng/node_modules/multicast-dns/index.js:40:24)
    at Socket.emit (node:events:390:28)
    at UDP.onMessage (node:dgram:939:8)
```

I've disabled mDNS as you recommended as I don't need to discover new devices and everything seems to work like I want it to. That's definitely a good enough fix for me at the moment. Thank you!
